DELETE FROM ROUTES WHERE ROUTE='to_b1'   AND MOMENT < addday(CURRENT_DATE, -15);
DELETE FROM ROUTES WHERE ROUTE='to_b2'   AND MOMENT < addday(CURRENT_DATE, -15);
DELETE FROM ROUTES WHERE ROUTE='from_b1' AND MOMENT < addday(CURRENT_DATE, -15);
DELETE FROM ROUTES WHERE ROUTE='from_b2' AND MOMENT < addday(CURRENT_DATE, -15);
